# Site settings
title: Photography Is Technology
email: photographyistechnology@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about photography and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://photographyistechnology.com" # the base hostname & protocol for your site
twitter_username: r4d1n
github_username:  r4d1n
instagram_username: r4d1n

# Build settings
markdown: kramdown
